//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a allus Code Generator.
//     Runtime Version: 1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

using System.ComponentModel.DataAnnotations;

namespace SportsClub.Common.BE
{


    public class PersonList : List<PersonBE>
    { }


    public partial class PersonBE 
    {
        #region [Private Members]
        private System.Int32 _PersonId;

        private Guid? _UserId;

        private System.String _DocType;

        private System.String _DocNumber;

        private System.String _Lastname;

        private System.String _Name;

        private short _Sex;

        private System.DateTime? _CreatedDate;

        private System.DateTime _DateOfBirth;

        private System.Byte[] _Photo;

        private System.Boolean _IsUserActive;

        private System.String _Street;

        private System.Nullable<short> _StreetNumber;

        private System.String _Floor;

        private System.Int32? _CountryId;

        private System.Int32? _ProvinceId;

        private System.Int32? _CityId;

        private System.String _Neighborhood;

        private System.String _mail;

        private System.String _Phone1;

        private System.String _Phone2;

        private System.String _Province;

        private System.String _City;

        private System.String _ZipCode;

        private System.DateTime? _LastAccessTime;

        private Guid? _LastAccessUserId;

        private System.Boolean _IsMember;

        private System.Int32? _FamilyGroupId;

        private System.Int32 _FamilyGroupMemberType;

        private System.Int32 _MaritalStatusId;

        private System.Int32? _MemberState;

        private System.Int32? _MemberCategoryCode;


        #endregion

        #region [Properties]
        #region [PersonId]
        public System.Int32 PersonId
        {
            get { return _PersonId; }
            set { _PersonId = value; }
        }
        #endregion


        #region [UserId]
        public Guid? UserId
        {
            get { return _UserId; }
            set { _UserId = value; }
        }
        #endregion


        #region [DocType]
        
        public System.String DocType
        {
            get { return _DocType; }
            set { _DocType = value; }
        }
        #endregion


        #region [DocNumber]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nro de documento es obligatorio")]
        public System.String DocNumber
        {
            get { return _DocNumber; }
            set { _DocNumber = value; }
        }
        #endregion


        #region [Lastname]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El apellido es obligatorio")]
        public System.String Lastname
        {
            get { return _Lastname; }
            set { _Lastname = value; }
        }
        #endregion


        #region [Name]
          [Required(AllowEmptyStrings = false, ErrorMessage = "El nombre es obligatorio")]
        public System.String Name
        {
            get { return _Name; }
            set { _Name = value; }
        }
        #endregion


        #region [Sex]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El género es obligatorio")]
        public short Sex
        {
            get { return _Sex; }
            set { _Sex = value; }
        }
        #endregion


        #region [CreatedDate]
          [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]   
        public System.DateTime? CreatedDate
        {
            get { return _CreatedDate; }
            set { _CreatedDate = value; }
        }
        #endregion
          
          
          
          public Guid? CreatedUserId { get; set; }

        #region [DateOfBirth]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fecha de nacimiento es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]      
        public System.DateTime DateOfBirth
        {
            get { return _DateOfBirth; }
            set { _DateOfBirth = value; }
        }
        #endregion


        #region [Photo]
        [System.Xml.Serialization.XmlElementAttribute("Photo", DataType = "base64Binary")]
        public Byte[] Photo
        {
            get { return _Photo; }
            set { _Photo = value; }
        }
        #endregion


        #region [IsUserActive]
        public System.Boolean IsUserActive
        {
            get { return _IsUserActive; }
            set { _IsUserActive = value; }
        }
        #endregion


        #region [Street]
        public System.String Street
        {
            get { return _Street; }
            set { _Street = value; }
        }
        #endregion


        #region [StreetNumber]
        public System.Nullable<short> StreetNumber
        {
            get { return _StreetNumber; }
            set { _StreetNumber = value; }
        }
        #endregion


        #region [Floor]
        public System.String Floor
        {
            get { return _Floor; }
            set { _Floor = value; }
        }
        #endregion


        #region [CountryId]
        public System.Int32? CountryId
        {
            get { return _CountryId; }
            set { _CountryId = value; }
        }
        #endregion


        #region [ProvinceId]
        public System.Int32? ProvinceId
        {
            get { return _ProvinceId; }
            set { _ProvinceId = value; }
        }
        #endregion


        #region [CityId]
        public System.Int32? CityId
        {
            get { return _CityId; }
            set { _CityId = value; }
        }
        #endregion


        #region [Neighborhood]
        public System.String Neighborhood
        {
            get { return _Neighborhood; }
            set { _Neighborhood = value; }
        }
        #endregion


        #region [mail]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Se requiere un correo electrónico")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^(([\w-]+\.)+[\w-]+|([a-zA-Z]{1}|[\w-]{2,}))@((([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])){1}|([a-zA-Z]+[\w-]+\.)+[a-zA-Z]{2,4})$", ErrorMessage = "No es un email válido.")]
        public System.String mail
        {
            get { return _mail; }
            set { _mail = value; }
        }
        #endregion


        #region [Phone1]
        public System.String Phone1
        {
            get { return _Phone1; }
            set { _Phone1 = value; }
        }
        #endregion


        #region [Phone2]
        public System.String Phone2
        {
            get { return _Phone2; }
            set { _Phone2 = value; }
        }
        #endregion


        #region [Province]
        public System.String Province
        {
            get { return _Province; }
            set { _Province = value; }
        }
        #endregion


        #region [City]
        public System.String City
        {
            get { return _City; }
            set { _City = value; }
        }
        #endregion


        #region [ZipCode]
        public System.String ZipCode
        {
            get { return _ZipCode; }
            set { _ZipCode = value; }
        }
        #endregion


        #region [LastAccessTime]
         [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]      
        public System.DateTime? LastAccessTime
        {
            get { return _LastAccessTime; }
            set { _LastAccessTime = value; }
        }
        #endregion
        
        

        #region [LastAccessUserId]
        public Guid? LastAccessUserId
        {
            get { return _LastAccessUserId; }
            set { _LastAccessUserId = value; }
        }
        #endregion


        #region [IsMember]
        public System.Boolean IsMember
        {
            get { return _IsMember; }
            set { _IsMember = value; }
        }
        #endregion


        #region [FamilyGroupId]
        public System.Int32? FamilyGroupId
        {
            get { return _FamilyGroupId; }
            set { _FamilyGroupId = value; }
        }
        #endregion


        #region [FamilyGroupMemberType]
        public System.Int32 FamilyGroupMemberType
        {
            get { return _FamilyGroupMemberType; }
            set { _FamilyGroupMemberType = value; }
        }
        #endregion


        #region [MaritalStatusId]
        public System.Int32 MaritalStatusId
        {
            get { return _MaritalStatusId; }
            set { _MaritalStatusId = value; }
        }
        #endregion


        #region [MemberState]
        //[Display("Estado del socio")]
        public System.Int32? MemberState
        {
            get { return _MemberState; }
            set { _MemberState = value; }
        }
        #endregion


        #region [MemberCategoryCode]
        public System.Int32? MemberCategoryCode
        {
            get { return _MemberCategoryCode; }
            set { _MemberCategoryCode = value; }
        }
        #endregion

        [Required(AllowEmptyStrings = false, ErrorMessage = "Fecha de alta al club es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]      
        public System.DateTime? DischargeDate { get; set; }

  
        public int MemberNumber { get; set; }
        #endregion



    }


}



