//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a allus Code Generator.
//     Runtime Version: 1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

using System.ComponentModel.DataAnnotations;

namespace SportsClub.Common.BE
{


    public class PersonSimpleViewList : List<PersonSimpleViewBE>
    { }


    public partial class PersonSimpleViewBE 
    {
        #region [Private Members]
        private System.Int32 _PersonId;
        private Guid? _UserId;
        private System.String _DocNumber;
        

        private System.Int32 _FamilyGroupMemberType;

        

        private System.Int32? _MemberState;

        private System.Int32? _MemberCategoryCode;


        #endregion

        #region [Properties]

        #region [Lastname]
        
        public System.String Lastname{get;set;}
        
        #endregion


        #region [Name]
        
        public System.String Name{get;set;}
        
        #endregion
        #region [PersonId]
        public System.Int32 PersonId
        {
            get { return _PersonId; }
            set { _PersonId = value; }
        }
        #endregion


        #region [UserId]
        public Guid? UserId
        {
            get { return _UserId; }
            set { _UserId = value; }
        }
        #endregion



        #region [DocNumber]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nro de documento es obligatorio")]
        public System.String DocNumber
        {
            get { return _DocNumber; }
            set { _DocNumber = value; }
        }
        #endregion




        #region [FamilyGroupMemberType]
        public System.Int32 FamilyGroupMemberType
        {
            get { return _FamilyGroupMemberType; }
            set { _FamilyGroupMemberType = value; }
        }
        #endregion
        

        #region [MemberState]
        //[Display("Estado del socio")]
        public System.Int32? MemberState
        {
            get { return _MemberState; }
            set { _MemberState = value; }
        }
        #endregion


        #region [MemberCategoryCode]
        public System.Int32? MemberCategoryCode
        {
            get { return _MemberCategoryCode; }
            set { _MemberCategoryCode = value; }
        }
        #endregion


        //public String Ege
        //{
        //    get { return Helper.GetEdad(this.DateOfBirth); }

        //}
        #endregion



          [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]      
        public DateTime DateOfBirth { get; set; }
          public String FullName
          {
              get
              {
                  return String.Concat(this.Lastname.Trim(), ", ", this.Name.Trim());
              }
          }

          public int? FamilyGroupId { get; set; }

          public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// Fecha de alta en el club. No necesaramente = fecha en la que se registra el socio
        /// </summary>
          public DateTime? DischargeDate { get; set; }


          public string StateName { get; set; }

          public short Sex { get; set; }
    }


}



