<?xml version="1.0" encoding="utf-8"?><Database Name="club" EntityNamespace="SportsClub.Linq" ContextNamespace="SportsClub.Linq" Class="clubDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=santana\SQLEXPRESS2008;Initial Catalog=club;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="clubConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MembersByMembershipFee" Member="MembersByMembershipFees">
    <Type Name="MembersByMembershipFee">
      <Column Name="MembershipFeeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CategoryDiscountPorcent" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="MembershipFee_MembersByMembershipFee" Member="MembershipFee" ThisKey="MembershipFeeId" OtherKey="MembershipFeeId" Type="MembershipFee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityPayments" Member="ActivityPayments">
    <Type Name="ActivityPayment">
      <Column Name="ActivityPaymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observation" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivitySchedulingMemberCategory" Member="ActivitySchedulingMemberCategories">
    <Type Name="ActivitySchedulingMemberCategory">
      <Column Name="ActivitySchedulingMemberCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MemberCategory_ActivitySchedulingMemberCategory" Member="MemberCategory" ThisKey="MemberCategoryId" OtherKey="MemberCategoryId" Type="MemberCategory" IsForeignKey="true" />
      <Association Name="ActivityScheduling_ActivitySchedulingMemberCategory" Member="ActivityScheduling" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivityScheduling" IsForeignKey="true" />
      <Association Name="ActivityScheduling_ActivitySchedulingMemberCategory1" Member="ActivityScheduling1" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivityScheduling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationGroupRoles" Member="ApplicationGroupRoles">
    <Type Name="ApplicationGroupRole">
      <Column Name="ApplicationRoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ApplicationGroup_ApplicationGroupRole" Member="ApplicationGroup" ThisKey="ApplicationGroupId" OtherKey="Id" Type="ApplicationGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationGroups" Member="ApplicationGroups">
    <Type Name="ApplicationGroup">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ApplicationGroup_ApplicationGroupRole" Member="ApplicationGroupRoles" ThisKey="Id" OtherKey="ApplicationGroupId" Type="ApplicationGroupRole" />
      <Association Name="ApplicationGroup_ApplicationUserGroup" Member="ApplicationUserGroups" ThisKey="Id" OtherKey="ApplicationGroupId" Type="ApplicationUserGroup" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUserGroups" Member="ApplicationUserGroups">
    <Type Name="ApplicationUserGroup">
      <Column Name="ApplicationUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ApplicationGroup_ApplicationUserGroup" Member="ApplicationGroup" ThisKey="ApplicationGroupId" OtherKey="Id" Type="ApplicationGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="StateI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="State_Localidad" Member="Localidads" ThisKey="StateI" OtherKey="StateId" Type="Localidad" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Province_City" Member="Province" ThisKey="ProvinceId" OtherKey="ProvinceId" Type="Province" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FamilyGroup" Member="FamilyGroups">
    <Type Name="FamilyGroup">
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TitularId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="FamilyGroup_MembershipFee" Member="MembershipFees" ThisKey="FamilyGroupId" OtherKey="FamilyGroupId" Type="MembershipFee" />
      <Association Name="FamilyGroup_Person" Member="Persons" ThisKey="FamilyGroupId" OtherKey="FamilyGroupId" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.fwk_ConfigManager" Member="fwk_ConfigManagers">
    <Type Name="fwk_ConfigManager">
      <Column Name="ConfigurationFileName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="[group]" Member="group" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="encrypted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.fwk_Param" Member="fwk_Params">
    <Type Name="fwk_Param">
      <Column Name="ParamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Culture" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Localidad" Member="Localidads">
    <Type Name="Localidad">
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="State_Localidad" Member="State" ThisKey="StateId" OtherKey="StateI" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedioContacto" Member="MedioContactos">
    <Type Name="MedioContacto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPerson" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberByActivities" Member="MemberByActivities">
    <Type Name="MemberByActivity">
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ActivityScheduling_MemberByActivity" Member="ActivityScheduling" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivityScheduling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberCategory" Member="MemberCategories">
    <Type Name="MemberCategory">
      <Column Name="MemberCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="AgeMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgeMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AntiguedadMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MemberCategory_ActivitySchedulingMemberCategory" Member="ActivitySchedulingMemberCategories" ThisKey="MemberCategoryId" OtherKey="MemberCategoryId" Type="ActivitySchedulingMemberCategory" />
    </Type>
  </Table>
  <Table Name="dbo.MembersByMembershipFee" Member="MembersByMembershipFee1s">
    <Type Name="MembersByMembershipFee1">
      <Column Name="MembershipFeeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="CategoryDiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MembershipFee_MembersByMembershipFee1" Member="MembershipFee" ThisKey="MembershipFeeId" OtherKey="MembershipFeeId" Type="MembershipFee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberShipFeeFamilyGroupSettings" Member="MemberShipFeeFamilyGroupSettings">
    <Type Name="MemberShipFeeFamilyGroupSetting">
      <Column Name="MemberShipFeeFamilyGroupSettingsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPorcent" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberState" Member="MemberStates">
    <Type Name="MemberState">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MemberState_Person" Member="Persons" ThisKey="Code" OtherKey="MemberState" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.PersonFiles" Member="PersonFiles">
    <Type Name="PersonFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContentFile" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Person_PersonFile" Member="Person" ThisKey="PersonId" OtherKey="PersonId" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profesional" Member="Profesionals">
    <Type Name="Profesional">
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfessionalRegistrationNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Profesional_ProfesionalByActivity" Member="ProfesionalByActivities" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="ProfesionalByActivity" />
      <Association Name="Profesional_Profesional_Profesion" Member="Profesional_Profesions" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="Profesional_Profesion" />
      <Association Name="Profesional_Profesional_Role" Member="Profesional_Roles" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="Profesional_Role" />
    </Type>
  </Table>
  <Table Name="dbo.ProfesionalByActivity" Member="ProfesionalByActivities">
    <Type Name="ProfesionalByActivity">
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActivityType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Profesional_ProfesionalByActivity" Member="Profesional" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="Profesional" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Provinces">
    <Type Name="Province">
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Province_City" Member="Cities" ThisKey="ProvinceId" OtherKey="ProvinceId" Type="City" />
    </Type>
  </Table>
  <Table Name="dbo.AccountNumber" Member="AccountNumbers">
    <Type Name="AccountNumber">
      <Column Name="AccountNumber" Member="AccountNumber1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreationDetails" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsTemporal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MembershipCanceledFee" Member="MembershipCanceledFees">
    <Type Name="MembershipCanceledFee">
      <Column Name="MembershipFeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayerMemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmmount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Interest" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="PeriodValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberShipFeeSettingsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryDiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="FamilyGroupDiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberByActivitiesView" Member="MemberByActivitiesViews">
    <Type Name="MemberByActivitiesView">
      <Column Name="Name" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MemberState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DischargeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MaritalStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DocNumber" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MemberActivitiesViewGrid" Member="MemberActivitiesViewGrids">
    <Type Name="MemberActivitiesViewGrid">
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivitiShedulingFullView" Member="ActivitiShedulingFullViews">
    <Type Name="ActivitiShedulingFullView">
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WeekDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekOfMotnths" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeStart" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TimeEnd" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ActivityTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EndDateEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ActivitySchedulingMemberCategoryAssigned" Member="ActivitySchedulingMemberCategoryAssigneds">
    <Type Name="ActivitySchedulingMemberCategoryAssigned">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MemberCategoryDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AgeMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgeMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FamilyGroupFullView" Member="FamilyGroupFullViews">
    <Type Name="FamilyGroupFullView">
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="TitularId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MemberShipFeeSettings" Member="MemberShipFeeSettings">
    <Type Name="MemberShipFeeSetting">
      <Column Name="MembershipFeeSettingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentPeriodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expiration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MembershipFeeSettingIdRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Interest" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="MonthCountToAlert" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CashFlowId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MemberShipFeeSetting_MembershipFee" Member="MembershipFees" ThisKey="MembershipFeeSettingId" OtherKey="MemberShipFeeSettingsId" Type="MembershipFee" />
      <Association Name="CashFlowConcept_MemberShipFeeSetting" Member="CashFlowConcept" ThisKey="CashFlowId" OtherKey="Id" Type="CashFlowConcept" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MembershipFee" Member="MembershipFees">
    <Type Name="MembershipFee">
      <Column Name="MembershipFeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmmount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Interest" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="DiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="FamilyGroupDiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="CategoryDiscountPorcent" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="MemberShipFeeSettingsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeriodValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="MembershipFee_MembersByMembershipFee" Member="MembersByMembershipFees" ThisKey="MembershipFeeId" OtherKey="MembershipFeeId" Type="MembersByMembershipFee" />
      <Association Name="MembershipFee_MembersByMembershipFee1" Member="MembersByMembershipFee1s" ThisKey="MembershipFeeId" OtherKey="MembershipFeeId" Type="MembersByMembershipFee1" />
      <Association Name="FamilyGroup_MembershipFee" Member="FamilyGroup" ThisKey="FamilyGroupId" OtherKey="FamilyGroupId" Type="FamilyGroup" IsForeignKey="true" />
      <Association Name="MemberShipFeeSetting_MembershipFee" Member="MemberShipFeeSetting" ThisKey="MemberShipFeeSettingsId" OtherKey="MembershipFeeSettingId" Type="MemberShipFeeSetting" IsForeignKey="true" />
      <Association Name="Person_MembershipFee" Member="Person" ThisKey="MemberId" OtherKey="PersonId" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityScheduling" Member="ActivitySchedulings">
    <Type Name="ActivityScheduling">
      <Column Name="ActivitySchedulingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WeekDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekOfMotnths" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeStart" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TimeEnd" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PaymentPeriodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndDateEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CashFlowId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ActivityScheduling_ActivitySchedulingMemberCategory" Member="ActivitySchedulingMemberCategories" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivitySchedulingMemberCategory" />
      <Association Name="ActivityScheduling_ActivitySchedulingMemberCategory1" Member="ActivitySchedulingMemberCategories1" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivitySchedulingMemberCategory" />
      <Association Name="ActivityScheduling_MemberByActivity" Member="MemberByActivities" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="MemberByActivity" />
      <Association Name="ActivityScheduling_ActivityScheduling" Member="ActivityScheduling2" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivityScheduling" Cardinality="One" />
      <Association Name="ActivityScheduling_ActivityScheduling" Member="ActivityScheduling1" ThisKey="ActivitySchedulingId" OtherKey="ActivitySchedulingId" Type="ActivityScheduling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashFlowConcepts" Member="CashFlowConcepts">
    <Type Name="CashFlowConcept">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ConceptType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelatedCashFlowConceptId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="CashFlowConcept_MemberShipFeeSetting" Member="MemberShipFeeSettings" ThisKey="Id" OtherKey="CashFlowId" Type="MemberShipFeeSetting" />
      <Association Name="CashFlowConcept_CashFlow" Member="CashFlows" ThisKey="Id" OtherKey="CashFlowId" Type="CashFlow" />
      <Association Name="CashFlowConcept_CashFlow1" Member="CashFlows1" ThisKey="Id" OtherKey="CashFlowConceptId" Type="CashFlow" />
    </Type>
  </Table>
  <Table Name="dbo.PersonFullView" Member="PersonFullViews">
    <Type Name="PersonFullView">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaritalStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupMemberType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Neighborhood" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Floor" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="StreetNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsUserActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DocNumber" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FamilyGroupName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MemberState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberCategoryCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberStateName" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="MemberStateDescription" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DischargeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MemberNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BlodTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DocType" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="DocNumber" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsUserActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="StreetNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Floor" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Neighborhood" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FamilyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FamilyGroupMemberType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaritalStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MemberState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberCategoryCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DischargeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MemberNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BlodTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Person_PersonFile" Member="PersonFiles" ThisKey="PersonId" OtherKey="PersonId" Type="PersonFile" />
      <Association Name="Person_MembershipFee" Member="MembershipFees" ThisKey="PersonId" OtherKey="MemberId" Type="MembershipFee" />
      <Association Name="FamilyGroup_Person" Member="FamilyGroup" ThisKey="FamilyGroupId" OtherKey="FamilyGroupId" Type="FamilyGroup" IsForeignKey="true" />
      <Association Name="MemberState_Person" Member="MemberState1" ThisKey="MemberState" OtherKey="Code" Type="MemberState" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profesional_Profesion" Member="Profesional_Profesions">
    <Type Name="Profesional_Profesion">
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfesionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Profesional_Profesion_Profesional_Profesion" Member="Profesional_Profesion2" ThisKey="ProfesionalId,ProfesionId" OtherKey="ProfesionalId,ProfesionId" Type="Profesional_Profesion" Cardinality="One" />
      <Association Name="Profesional_Profesional_Profesion" Member="Profesional" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="Profesional" IsForeignKey="true" />
      <Association Name="Profesional_Profesion_Profesional_Profesion" Member="Profesional_Profesion1" ThisKey="ProfesionalId,ProfesionId" OtherKey="ProfesionalId,ProfesionId" Type="Profesional_Profesion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profesional_Roles" Member="Profesional_Roles">
    <Type Name="Profesional_Role">
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RolId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Profesional_Profesional_Role" Member="Profesional" ThisKey="ProfesionalId" OtherKey="ProfesionalId" Type="Profesional" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProfesionalFullView" Member="ProfesionalFullViews">
    <Type Name="ProfesionalFullView">
      <Column Name="ProfesionalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinceNAme" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DocNumber" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProfessionalRegistrationNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashFlow" Member="CashFlows">
    <Type Name="CashFlow">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ammount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Concept" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ParamModuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SportClubGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CashFlowId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CashFlowConceptId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ConceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CashFlowConcept_CashFlow" Member="CashFlowConcept" ThisKey="CashFlowId" OtherKey="Id" Type="CashFlowConcept" IsForeignKey="true" />
      <Association Name="CashFlowConcept_CashFlow1" Member="CashFlowConcept1" ThisKey="CashFlowConceptId" OtherKey="Id" Type="CashFlowConcept" IsForeignKey="true" />
    </Type>
  </Table>
</Database>